services:
  jenkins:
    build: .
    user: root
    ports:
      - 8070:8080
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/var/jenkins_home/workspace  # Monte le dossier workspace
    networks:
      - critik_network

networks:
  critik_network:
    external: true
    name: critik_network
